### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by fixer1234** [BobVul/SEReopenReviewWarning#1]
Thanks for tackling this.  Unfortunately, I can't get it to work.  I started with Tampermonkey in Vivaldi (Chromium-based).  Opened one of the questions identified on Root Access that failed review and is still closed.  It didn't add any message.  On Firefox, the only thing that reliably handles user scripts for me is violentmonkey.  Loaded the script and got throttled:

error_id	502
error_message	"too many requests from this IP, more requests available in 38343 seconds"
error_name	"throttle_violation"

So I can try again in half a day.  Anything I can do at my end?

**Comment by BobVul** [comment]
Hm. [This page](https://superuser.com/questions/1456570/mysql-cannot-access-files-after-backup-of-data-and-restore-of-data) works for me on Violentmonkey on Firefox. (Note that post-WE Greasemonkey and Violentmonkey handle scripts differently, and VM has better compat with older scripts - but the way I wrote this one GM and VM should both work.)

There shouldn't be any throttling: I don't use the API, I just hit the timeline HTML page and scrape that. And then only once per question page request, which should be well within "normal user" frequency. Where do you see the throttling error from?

**Comment by BobVul** [comment]
Should be fixed for Tampermonkey now. It needed an explicit permission grant for `unsafeWindow`.
